"""
FastMCP Server Template
=======================
Generated by the fastmcp-scaffolder skill.

Usage:
    # stdio transport (local development)
    python server.py

    # HTTP+SSE transport (remote deployment)
    # Change mcp.run() at the bottom to:
    #   mcp.run(transport="sse", host="0.0.0.0", port=3000)
"""

import os
import logging
from pathlib import Path
from mcp.server.fastmcp import FastMCP

# --- CONFIGURE LOGGING (NEVER use print with stdio transport) ---
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
logger = logging.getLogger(__name__)

# --- CREATE THE SERVER ---
mcp = FastMCP("my-server")


# ==============================================================
# TOOLS — Actions the AI can perform (has side effects)
# ==============================================================

@mcp.tool()
def example_tool(query: str) -> str:
    """
    Describe what this tool does. Be specific.
    The AI reads this docstring to decide when and how to call the tool.
    """
    try:
        # Your implementation here
        result = f"Processed: {query}"
        return result
    except Exception as e:
        # Return errors as text so the AI can read and explain them
        return f"Error: {e}"


# ==============================================================
# RESOURCES — Read-only data the AI can access
# ==============================================================

@mcp.resource("myapp://docs/guide")
def get_guide() -> str:
    """User Guide — read-only documentation the AI can reference."""
    return "This is the user guide content."


# ==============================================================
# PROMPTS — Reusable prompt templates
# ==============================================================

@mcp.prompt()
def summarize(topic: str) -> str:
    """Summarize a topic in 2-3 sentences."""
    return f"Please provide a concise 2-3 sentence summary of: {topic}"


# ==============================================================
# FILE ACCESS PATTERN (include ONLY if server accesses files)
# ==============================================================

# Uncomment and configure if your server needs to read/write files:
#
# ALLOWED_ROOT = Path(os.environ.get("ALLOWED_ROOT", Path.home())).resolve()
#
# def safe_path(requested: str) -> Path:
#     """Resolve path and verify it stays within ALLOWED_ROOT."""
#     resolved = Path(requested).resolve()
#     if not str(resolved).startswith(str(ALLOWED_ROOT)):
#         raise ValueError("Access denied: path is outside the allowed directory")
#     return resolved
#
# @mcp.tool()
# def read_file(file_path: str) -> str:
#     """Read and return the text content of a file.
#     Provide the absolute path of the file to read."""
#     try:
#         target = safe_path(file_path)
#         return target.read_text(encoding="utf-8")
#     except Exception as e:
#         return f"Error: {e}"


# ==============================================================
# START THE SERVER
# ==============================================================

if __name__ == "__main__":
    logger.info("Starting MCP server...")
    # Default: stdio transport (for local development / Claude Desktop)
    mcp.run()

    # For remote deployment, use HTTP+SSE instead:
    # mcp.run(transport="sse", host="0.0.0.0", port=3000)
